### ISSUE TITLE
Back/forward mouse buttons

### ISSUE THREAD

**Issue by xendk** [zulip/zulip-desktop#1015]
**Describe the bug**
Forward/back buttons on mouse doesn't work.

**To Reproduce**
Buttons have no effect.

**Expected behavior**
The same as using alt+left/right-arrow.

**Desktop (please complete the following information):**
 - Operating System: 
Ubuntu 20.04.1x64
 - Zulip Desktop Version:
5.4.0

**Additional context**

Tim pointed out that this might be relevant:
https://github.com/electron/electron/issues/6996

**Comment by Skyedra** [comment]
Just adding that this is still an issue present on desktop version v5.11.1 (Ubuntu 24.04)

(Possibly same issue/feature request as more recently filed #1270?)

**Comment by timabbott** [comment]
Hmm, it does look like upstream Electron fixed this and that fixed it for some other Electron apps. Unclear why that fix hasn't applied to the Zulip app.

**Comment by andersk** [comment]
I see no evidence that upstream Electron fixed this. electron/electron#6996 was closed as wontfix, with the suggested workaround being a native C++ module that binds libX11 directly, with very few downloads, no maintenance in 5 years, and presumably no Wayland support.

**Comment by timabbott** [comment]
https://github.com/electron/electron/pull/15441 and https://github.com/irccloud/irccloud-desktop/issues/86 were the things that suggested to me this was fixed upstream.

**Comment by andersk** [comment]
I now have the hardware to confirm that this is still broken. We probably need to wire up the new `app-command` events to the correct webview ourselves.

**Comment by G2G2G2G** [comment]
This doesn't work on windows nor linux (don't have apple to test).
All other electron apps haven't had issues with this since like 2018 and earlier on linux.
IIRC we fixed element-desktop pre-covid and discord also got fixed around that time.


What is being done here? It is very easy to get this to work.

Press ctrl+shift+I in zulip desktop app to open dev console

You need to run this to get out of electrons garbage security or whatever they call it
```
document.querySelector('webview').openDevTools();
```

Then add this simple event listener
```
window.addEventListener('mousedown', (e) => {
    if (e.button === 3) {
        console.log("➡️ Mouse4 detected.");
        e.preventDefault();
        window.history.back();
    }
});
```

Whatever issue zulip is having it is very unlikely electron would bother to fix it if it even is an electron issue.
Can we just throw this event in there and call it done? This is a very used hotkey and silly to not just have fixed it so long ago..
