### ISSUE TITLE
When desktop notifications are off, a stream post should not "Activate" Zulip

### ISSUE THREAD

**Issue by lmckenzi** [zulip/zulip-desktop#299]
This is a request for the Electron Windows client.  I run with the Windows menu bar "hidden".  When an application 'activates', it causes the menu bar to become visible and it won't disappear until you click on the menu bar.  I *want* it to do that when there's a notification, but I don't want it to do that for streams that have notifications turned off or if I've muted all notifications.  You can see here what it looks like when both Skype and Zulip have 'activated'.  (I have not idea what the proper term is for 'activation' - entirely possible I'm using the wrong word.)
![image](https://user-images.githubusercontent.com/4911489/30497992-e630fb24-9a09-11e7-92f4-e284f4bcdfaa.png)

**Comment by grahamegrieve** [comment]
ha. personally, I *like* the current behavior

**Comment by lmckenzi** [comment]
Then we can make it configurable.  But being interrupted 10-20 times an hour by low-priority threads is not helpful.  As I result I use the web client and I don't get task-bar notifications for anything.

**Comment by akashnimare** [comment]
@lmckenzi do you mean the flashing taskbar icon - 

<img src="https://user-images.githubusercontent.com/26190934/28449543-207b3e5c-6de1-11e7-98e6-702290cc650d.gif"/>

**Comment by lmckenzi** [comment]
It doesn't flash on my machine, but that may be a difference between whether the task bar is set to auto-hide or not

**Comment by ManthanoPoly** [comment]
@lmckenzi  which Windows version are you running?

**Comment by lmckenzi** [comment]
Windows 10

**Comment by akashnimare** [comment]
@lmckenzi this is fixed in https://github.com/zulip/zulip-electron/commit/e6dbff995b42851684e26b64657954ed237154a7. Now you can control whether you want flashing of taskbar icon or not.

![image](https://user-images.githubusercontent.com/2263909/32344081-9ff0257a-c02b-11e7-8644-0407020e6bd9.png)

**Comment by lmckenzi** [comment]
I tested this and unfortunately it doesn't work.  I turned "Flash taskbar on new message", but I still get flashes when new messages arrive.

Also, the functionality isn't really what's desired.  I *want* flashes on new messages, but I only want them when two conditions are met: the new message is on a stream that's set to have it happen (this could layer off desktop notifications or audible notifications or it could be a new per/tracker setting); and I haven't asked to temporarily mute all flashes.  For example, if I'm presenting or otherwise need to not be disturbed.  This needs to be a fairly quick action - not something that involves drilling deeply into menus

**Comment by akashnimare** [comment]
> I tested this and unfortunately it doesn't work. I turned "Flash taskbar on new message", but I still get flashes when new messages arrive.

@lmckenzi thanks for testing it out. Let's fix the setting option first and then we can improve it later. Can you make sure that you're on v1.8.1? If I disable "Flash taskbar on new message" setting on my Windows 10 then the Zulip taskbar icon doesn't flash on new incoming notification.

**Comment by lmckenzi** [comment]
Yes. Running Zulip 1.8.1 on Windows 10 Pro (Build 12699)
