### ISSUE TITLE
Handle corrupted domain.json files gracefully

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-desktop#310]
We got a report of a user having the Zulip desktop app just hang on startup.

It turned out the cause was their `domain.json` file was totally corrupted JSON and didn't open (it was filled with `\0` characters).

We should probably do some combination of the following.
(0) See if we have any bugs that might cause this corruption (e.g. if we open the file for writing before doing a network request and only after the network request returns, write to the file).
(1) Quickly look into whether there's a standard Electron storage library we should be using that does this sort of error-handling for us.  That might be the best plan.
(2) If not, make the code that reads `domain.json` handle errors in a reasonable way.  We probably want to show some sort of user-facing error like "The Zulip app's configuration file (path) seems to be corrupted; this is very rare and likely caused by problems with your filesystem.." with a button "Clear state" or something.  And we should log something to e.g. Sentry so we can track how often it happens.

**Comment by akashnimare** [comment]
@geeeeeeeeek is it possible that reloading the DB while updating the saved server causing this issue. Do we really need to reload db here - 
https://github.com/zulip/zulip-electron/blob/0a1866abb58a1bba4200e790161eb357b39ac3e9/app/renderer/js/utils/domain-util.js#L49
https://github.com/zulip/zulip-electron/blob/0a1866abb58a1bba4200e790161eb357b39ac3e9/app/renderer/js/utils/domain-util.js#L218
https://github.com/zulip/zulip-electron/blob/master/app/renderer/js/utils/domain-util.js#L212-L221

**Comment by akashnimare** [comment]
Short term solution - If `domain.json` or `setting.json` gets corrupted for some reason then re-create both the files so that users don't get the hanging app window.

Long term solution - Find the root cause of why the files are getting corrupted and fix that.

**Comment by akashnimare** [comment]
Made some changes in error handling of corrupted config files. From now on, if the config files (settings.json, domain.json) gets corrupted for some reason then we re-initialize those files that way user won't get hanging app window. For an example if the domain.json gets corrupted -
* First we're showing the error dialog -

![image](https://user-images.githubusercontent.com/2263909/34342361-dbaab20c-e9d3-11e7-8483-9c10d43ead58.png)

* Deletes and re-init domain.json. Also logging the errors for better debugging.
FYI @timabbott.

**Comment by timabbott** [comment]
"organization" is spelled incorrectly as "organisation" in one of the places there.  Also, "readd" isn't a word.  

@rishig can you help with the language here?

**Comment by priyank-p** [comment]
That's an outdated picture, fixed in latest master. The dialog is now as follows
https://github.com/zulip/zulip-electron/blob/aa8e99b7a629062e5360bbabd3367815ad02073a/app/renderer/js/utils/domain-util.js#L247-L249

**Comment by vsvipul** [comment]
Is this fixed? If so, i think, it can be closed.

**Comment by akashnimare** [comment]
> Is this fixed? If so, i think, it can be closed.

@vsvipul nope, I still get this error once in a while but not sure how to reproduce.

**Comment by timabbott** [comment]
@shubham-padia do you want to check if this still exists, and if so, give it the same treatment as #1404?
