### ISSUE TITLE
Can't log out under File menu or with CTRL-L

### ISSUE THREAD

**Issue by Andy3142** [zulip/zulip-desktop#328]
Is this really the place to post newbie end user help requests ...? If not my apologies and where do I go; if so, it's very futuristic! 
I just installed Zulip to test it. I can't log out with File>Log Out or with CTRL-L. I do it over and over, nothing happens. But I log out as expected with Settings Icon > Log out.  Then I log back in, fail to log out via File and CTRL-L, succeed again via Settings Icon ... round and round. I did this 4 times and it is the same every time. Looks like a bug.
					-
					Zulip 1.5.0
					Electron 1.6.14
					win32 x64 10.0.15063
Regards
Andy

**Comment by akashnimare** [comment]
@Andy3142 Okay, so I can't reproduce this on Windows 10. Have you downloaded the app from https://zulipchat.com/apps? Also, can you paste the console logs `View > Toggle DevTools for Active Tab > Console`

**Comment by Andy3142** [comment]
@akashnimare Yes, that's where I got the app. I hate to say this, but should something HAPPEN when I do View > Toggle DevTools for Active Tab  ? - because nothing happens at all. If I do View > Toggle DevTools for Zulip App, then I get a tools windows, but not for the Active Tab. 
Two thoughts. One, when I installed the app I was logged in on the web; could that have confused the installation? Also, there is a funny visual blemish on the app, it is an expanding blue circle, kind of a "processing, please wait" icon which re-appears every time I start the app. Again, corrupted installation?
I could uninstall-reinstall, or not, whichever you find more helpful.

**Comment by cedricium** [comment]
@Andy3142 the `Toggle DevTools for Active Tab` creates a separate window from the Zulip app, by any chance did you miss it (hidden behind the Zulip app window or on another monitor maybe)?

AFAIK, being logged in to the browser should not affect the desktop app download/installation.

**Comment by Andy3142** [comment]
@Cedricum When I do ctrl-shift-I I get an immediately visible pane, when I do ctrl-shift-U, nothing happens at all.

**Comment by Andy3142** [comment]
I uninstalled and re-installed and most problems have ended. File > logout works, and the floating windows for tab tools appears OK. So that was a corrupt installation. However, there is still a floating circular blob, which looks like a "processing, please wait" icon, stuck to the tab. I guess this is probably corrupt data (my data persisted through the unistall), so please could someone tell me how to do a total uninstall including user data,?, and I'll try a third time.

**Comment by akashnimare** [comment]
@Andy3142 can you remove `C:\Users\[name]\AppData\Roaming\Zulip` directory and start app again?

**Comment by cedricium** [comment]
@akashnimare sounds like this might relate to #310? Before @Andy3142 removes the directory, should we investigate further?

**Comment by akashnimare** [comment]
Hmm, I don't think it's #310 since he can run the server and logout using the setting gear icon (In #310 app doesn't load at all it only show the loading icon). 

> But I log out as expected with Settings Icon > Log out. Then I log back in, fail to log out via File and CTRL-L, succeed again via Settings Icon

But let's see what's his `domain.json` looks like. @Andy3142 can you please paste the content of `C:\Users\[name]\AppData\Roaming\Zulip\domain.json` before doing https://github.com/zulip/zulip-electron/issues/328#issuecomment-341788275.

**Comment by Andy3142** [comment]
Here's the json file and a screen snip of the funny pulsating icon.  While I do now get the "Dev tools for tab" tab, the Console tab within that is void, so I don't see how to upload the log as requested above.  Console tab says at the top

`Socket connected [transport=websocket]  webpack:///./static/js/blueslip.js` 

but apart from that the pane is empty. I assumed there must be a way to upload the entire Dev Tools function in its entirety, but if there is, I can't find it. 

Does anyone want more information, or shall I go ahead with the clean re-install?

![temp del zulip bug 1](https://user-images.githubusercontent.com/33326823/32501256-76a8e876-c3cf-11e7-88d6-29ff19b3e1b1.PNG)

`{
    "domains": [
        {
            "icon": "C:\\Users\\andre\\AppData\\Roaming\\Zulip/server-icons/4025106633",
            "url": "https://oshouk.zulipchat.com",
            "alias": "Osho UK Zulip"
        }
    ]
}`

**Comment by akashnimare** [comment]
Okay, this looks good. Can you also paste the console logs of app? You can find it in  `Menu > View Toggle DevTools for Active Tab` and then `developer tools > console tab`.

![image](https://user-images.githubusercontent.com/2263909/32502882-e3e8189e-c401-11e7-9ac2-de57e1755bd2.png)

**Comment by Andy3142** [comment]
@akashnimare View Dev Tools for Zulip App > Console is also 100% blank.
Just for my curiousity, is there not some way to send the entire Dev Tools output as some kind of xml file or something like that?

**Comment by akashnimare** [comment]
> Just for my curiousity, is there not some way to send the entire Dev Tools output as some kind of xml file or something like that?

As of now, nope!

**Comment by akashnimare** [comment]
I think it's good idea to write dev tools logs for active tab and zulip tab in a file.

**Comment by akashnimare** [comment]
@Andy3142 is the app working fine? Are you able to logout using `CTRL+L` ?

**Comment by Andy3142** [comment]
@akashnimare  The situation is as per my post of 6 days ago: following the reinstall, the app works fine including CTRL-L, so the problem was a corrupt install. HOWEVER there is still a circular, slowly-pulsating blue circle stuck to the screen, per previous image file.  I strongly assume this circle is a bug. View > devtools for app > console is blank. Until today, devtools for tab > console has always also been blank, but today for the first time it has an entry and is here: 
`common-70e44c863cabfbef34e4.83a26c9b6104.js:1 Socket connected [transport=websocket]
common-70e44c863cabfbef34e4.83a26c9b6104.js:1 Added user late: user_id=100090 email=new-user-bot@zulip.com
(anonymous) @ common-70e44c863cabfbef34e4.83a26c9b6104.js:1
`
My next plan would be to do a 100% clean install and see if the puslating circle goes away; I'm waiting for your go-ahead to do the clean install. Shall I do this now?

**Comment by akashnimare** [comment]
@Andy3142 Okay, do a clean install and let me know if everything works as expected.

**Comment by Andy3142** [comment]
No good, the problem persists.  I deleted Users>[me]>appdata>roaming>Zulip, restarted, downloaded again, re-installed, entered my domain, and still get the floating pulsating blue circle. I did that whole procedure a second time (well, I didn't download yet again) and still get the maddening pulsating circle. It appears in slightly different randomish points on the screen and it appears in every stream. It turns out that if I click it, I get a message saying "click anywhere in a message to reply" so it is at least linked to an intended feature. However the way it behaves can surely not be intended? Please can you confirm it's not meant to do this?

I have zero real data in Zulip at present, and all the apparent users are variants of my own email for test purposes, ie, I am the one and only actual user. So if you can, delete all the data, indeed delete the domain, and let's see if that gets rid of it.

**Comment by akashnimare** [comment]
Can you please upload a gif/screenshots of the issue so that I can see what's going on!

**Comment by Andy3142** [comment]
I already did, but here are 2 more.
![2-capture](https://user-images.githubusercontent.com/33326823/32740994-a8ee5196-c89c-11e7-8b16-63b6d9d7481e.PNG)
![1-capture](https://user-images.githubusercontent.com/33326823/32740995-a90ea9be-c89c-11e7-95b9-9082e22a3641.PNG)

I can't record a gif easily but a second, lighter blue, circle expands out from this one until it's about double the diameter, then vanishes, and that repeats maybe a bit slower than once a second. It is very irritating. It always appears toward the right of the window, and moves up and down  if I scroll. It seems to like being on the bottom margin on the last message, but it's not always there.

**Comment by akashnimare** [comment]
I'm sure this is not coming form desktop app. @rishig, @timabbott any idea from where it's coming?

**Comment by Andy3142** [comment]
Forgive me being naive,  but could this be corrupt user data caused by the original corrupt install?

**Comment by akashnimare** [comment]
I don't think so. BTW do you see this issue in web app?

**Comment by Andy3142** [comment]
I'm attempting to log in to the web app but apparently I can't just simply log in; when I click "login" on zulipchat,com > login, I get taken to this page:   https://zulipchat.com/accounts/find/
where I enter my email and and am now waiting a long time for a login email. If this is correct behaviour then I am simply waiting for an email, these took many hours to arrive when I set up the account originally. But is this correct behaviour? because zulipchat > find accounts takes me to that identical page.
Either way, I'm waiting for a login email and when that arrives, I'll look for the blob in the browser.

**Comment by timabbott** [comment]
OK, so there's a few things going on here:
* The login link on the zulipchat.com homepage is a bug, fixed here: https://github.com/zulip/zulip/commit/a86968cd44d931c76dfecd0426825b580b47598a
* zulipchat.com doesn't host any Zulip organizations, though e.g. subdomain.zulipchat.com does.  The "Find account" thing will work if your account is part of a subdomain.zulipchat.com organization.  Perhaps the Zulip account you have is with some other Zulip server, which zulipchat.com can't find for you?
* The "Find account" feature only sends an email if an account exists.  There's an open project to change this to avoid the exact confusion you're having (and instead have it send a "we can't find your account" email).

**Comment by Andy3142** [comment]
(1) @timabbott  as far as I can see the login bug is not fixed, it is a bug - I try to login and I get sent to the "find" page - surely that is an active bug?
(2) @akashnimare, I logged in on the web and the blog is still there.  So, you can log in as me if you like and you too should see it:
email islam@livenowlovenowhealnow.co.uk , p/w demo-1234

**Comment by akashnimare** [comment]
@Andy3142 what Zulip server address you're trying to connect to?

**Comment by timabbott** [comment]
For (1), I'd just made the change in the codebase; it hasn't been deployed to production yet.  After the change, that page won't have a login link anymore (that's the bug).

**Comment by Andy3142** [comment]
@akashnimare Sorry, should have said: oshouk.zulipchat.com

**Comment by akashnimare** [comment]
![image](https://user-images.githubusercontent.com/2263909/32801095-0ef2d768-c9a2-11e7-8709-7b5ee81ca094.png)

![image](https://user-images.githubusercontent.com/2263909/32801148-3c2dc936-c9a2-11e7-9f37-1db0d170bd25.png)

Well, those popups are shown when you first visit the server. It's a feature not a bug. They just help you to understand the features of Zulip. You just have to press `got it` and they will be gone forever. @timabbott do we have an option to skip this tutorial thing?

**Comment by Andy3142** [comment]
I get it that the square popups are a feature. It's not obvious that the purpose of the blob is to lead to an optional popup. Are you therefore also saying the funny pulsating blob with its irregular position, to-me irritating rhythm, inconsistent response to scrolling, and with the appearance of being a "please wait, processing in progress" rather than a "click here for option information" icon is an intended feature which is working as intended?

**Comment by timabbott** [comment]
Thanks for your feedback @Andy3142!  The sort of pulsing indicator is a common way do suggest you click on something in a modern tutorial.

That said, @brockwhittaker @rishig FYI; the feedback on the tutorial is something I hadn't heard before.

I think we should return discussion on issue to be about the actual desktop app problem (something to do with `ctrl-L`?).

**Comment by akashnimare** [comment]
@Andy3142 are you able to logout using `CTRL-L` from desktop app?

**Comment by akashnimare** [comment]
Closing due to inactivity. Please re-open if it happens on [1.7.0](https://github.com/zulip/zulip-electron/releases/tag/v1.7.0).
