### ISSUE TITLE
Zulip app closes unexpectedly on Windows 10

### ISSUE THREAD

**Issue by winmasta** [zulip/zulip-desktop#584]
---

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubutnu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Start Zulip app on windows 10, wait some seconds (5-30) and app will be closed without any actions from user. Affects 2 of 4 our computers.
- **Relevant error messages and/or screenshots**:
No error messages from Zulip or Windows.

**Comment by akashnimare** [comment]
@winmasta yeah, I have seen this issue. The main reason behind this is they might have downloaded the `v2.3.7-beta` which was meant to be a pre/beta-release and not stable (I wrongly uploaded the beta installer in the latest release v2.3.8). Can you tell your folks to uninstall the app they are using and download the latest stable release from [here](https://zulipchat.com/apps/windows) and the problem will go away?

**Comment by lisasinclair** [comment]
Also experiencing on v2.3.8 on Windows 10. 
Attempted reinstall earlier this week and product was stable until this morning.

**Comment by j0hannesr0th** [comment]
Same here - Zulip closes itself or crashes unexpectedly after a few seconds.

I can confirm @lisasinclair statement. A reinstall worked until this morning.

Now I fully uninstalled Zulip-Electron and reinstalled it again but it doesn't change anything - Zulip doesn't work.

Windows 10: 1803 Build 17134.345
Zulip-Electron: v2.3.82

**Comment by Mattes1000** [comment]
It seem that there is a problem with the "auto update" of the app.

I had the 2.3.8 installed and the app crashed after a view seconds.
I downloded the version 2.3.82 and replaced the Folder c:\Program Files\Zulip 
Now all works fine.

A few days ago, when the Version 2.3.8 was released, the same error occured.
I had the version 2.3.7beta and the app crashed after a few seconds.

**Comment by akashnimare** [comment]
@hmr-it-jr, @lisasinclair, @winmasta please update the app to [v2.3.82](https://github.com/zulip/zulip-electron/releases/download/v2.3.82/Zulip-Web-Setup-2.3.82.exe) manually, it should fix the auto-update issues.

**Comment by lisasinclair** [comment]
I'm already on 2.3.82 and it's still happening :(

**Comment by j0hannesr0th** [comment]
@akashnimare as I wrote in my previous post I already use the latest version:
> Zulip-Electron: v2.3.82

The problem is still present.

**Comment by akashnimare** [comment]
Wierd, I have followed the following steps and the app works fine for me on Windows 10 
* Uninstalled Zulip app (I was on v2.3.8)
* Installed the latest version from [this](https://github.com/zulip/zulip-electron/releases/download/v2.3.82/Zulip-Web-Setup-2.3.82.exe) link (v2.3.82)
* Started the app and no issues

![image](https://user-images.githubusercontent.com/2263909/46857272-30f14f00-ce26-11e8-8adf-1492be2da7e5.png)

**Comment by lisasinclair** [comment]
I did the same at the beginning of the week and it worked fine until today. Give it a couple of days and it may fail for you too >.<

Am using zulipchat as the host which may make a difference?

**Comment by akashnimare** [comment]
> I did the same at the beginning of the week and it worked fine until today

@lisasinclair can you repeat the steps again please since we release the `v2.3.82` yesterday only? 

> Am using zulipchat as the host which may make a difference?

No, I don't think so.

**Comment by lisasinclair** [comment]
Mia Culpa, I got it wrong. Installed 2.3.82 and will see how it goes.
Have a great weekend

**Comment by akashnimare** [comment]
Yeah, `v2.3.82` (latest stable release) and `v2.3.8` are two different versions.

**Comment by j0hannesr0th** [comment]
> 
> 
> Wierd, I have followed the following steps and the app works fine for me on Windows 10
> 
>     * Uninstalled Zulip app (I was on v2.3.8)
> 
>     * Installed the latest version from [this](https://github.com/zulip/zulip-electron/releases/download/v2.3.82/Zulip-Web-Setup-2.3.82.exe) link (v2.3.82)
> 
>     * Started the app and no issues
> 
> 
> ![image](https://user-images.githubusercontent.com/2263909/46857272-30f14f00-ce26-11e8-8adf-1492be2da7e5.png)

Works for me, thanks a lot!

**Comment by jevad** [comment]
I had the same problem on Windows 7.  I checked the logs, and it looked like the automatic update sub-system was having issues that were taking out the entire VM.  So I updated to the latest version manually, and that fixed it for a few days.  Then the problem returned, and this time, updating manually did not fix the problem.  

However, I did find a workaround:  Turn off auto-update:  As soon as you open the the Zulip client application (remember, time is of the essence -- you do not have much time before the application will spontaneously close):

* Click on the settings gear icon in the lower right.  
* Click on "General" on the Settings page.
* Then de-select "Enable auto updates"

The system then spontaneously closed one more time.  But after that, it no longer spontaneously closed.
That fixed it for me.  Your mileage may vary.

**Comment by akashnimare** [comment]
@jevad is it possible for you to share the logs so that I can see what's wrong? You can send it on `akash[at]zulipchat[dot]com`

**Comment by reimerpeter** [comment]
I had this problem back in October 2018 however a reinstall fixed it.

The problem came back today although I was able to turn off Enable Auto Updates after 3 tries and now Zulip is no longer crashing in 3 seconds. 

I can send logs if you tell me where they are in Windows 10.

**Comment by emmanuelflores-sk** [comment]
Echoing reimperter above, Zulip started crashing on me not long after it's started up. Somewhere between 5 to 30 seconds.

**Comment by abhigyank** [comment]
@reimerpeter You can access the logs from `Tools->Show App Logs` and mail it to akash[at]zulipchat[dot]com.
It has something to we with the auto updates, since we had released a new update today. For now we have pull the update down so it should work properly.

**Comment by reimerpeter** [comment]
I found it in Tools, Download App Logs.
I will email it to you.
Thanks!

**Comment by abhigyank** [comment]
Closing since not reproduced in  a long time and we move repository to address this issue after v2.3.82.
